import { type CourseRecord } from "@/types/courseTypes";

export const coursesData: CourseRecord[] = [
  {
    "_id": "course_001",
    "title": "Course Title 1: Master Music",
    "description": "This is an in-depth course on Music. You will learn the fundamentals and advanced topics from User 6 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course1/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 99.99,
    "level": "advanced",
    "instructor": "user_006",
    "category": "cat_008",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 4.38,
    "totalReviews": 438,
    "totalStudentsEnrolled": 34,
    "totalDurationInMinutes": 429,
    "totalRevenueInstructor": 892,
    "totalRevenueAdmin": 325,
    "slug": "course-title-1-master-music",
    "createdAt": "2025-08-30T08:50:49.075Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Music",
    "instructorName": "User 6 Fullname"
  },
  {
    "_id": "course_002",
    "title": "Course Title 2: Master Data Science",
    "description": "This is an in-depth course on Data Science. You will learn the fundamentals and advanced topics from User 15 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course2/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 0,
    "level": "beginner",
    "instructor": "user_015",
    "category": "cat_002",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 0,
    "totalReviews": 0,
    "totalStudentsEnrolled": 134,
    "totalDurationInMinutes": 880,
    "totalRevenueInstructor": 4302,
    "totalRevenueAdmin": 658,
    "slug": "course-title-2-master-data-science",
    "createdAt": "2025-05-23T03:05:55.695Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Data Science",
    "instructorName": "User 15 Fullname"
  },
  {
    "_id": "course_003",
    "title": "Course Title 3: Master Data Science",
    "description": "This is an in-depth course on Data Science. You will learn the fundamentals and advanced topics from User 8 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course3/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 99.99,
    "level": "beginner",
    "instructor": "user_008",
    "category": "cat_002",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 3.98,
    "totalReviews": 58,
    "totalStudentsEnrolled": 505,
    "totalDurationInMinutes": 728,
    "totalRevenueInstructor": 2772,
    "totalRevenueAdmin": 305,
    "slug": "course-title-3-master-data-science",
    "createdAt": "2025-11-13T17:05:33.813Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Data Science",
    "instructorName": "User 8 Fullname"
  },
  {
    "_id": "course_004",
    "title": "Course Title 4: Master Music",
    "description": "This is an in-depth course on Music. You will learn the fundamentals and advanced topics from User 6 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course4/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 29.99,
    "level": "beginner",
    "instructor": "user_006",
    "category": "cat_008",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 4.9,
    "totalReviews": 83,
    "totalStudentsEnrolled": 833,
    "totalDurationInMinutes": 418,
    "totalRevenueInstructor": 935,
    "totalRevenueAdmin": 726,
    "slug": "course-title-4-master-music",
    "createdAt": "2026-03-01T12:45:25.111Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Music",
    "instructorName": "User 6 Fullname"
  },
  {
    "_id": "course_005",
    "title": "Course Title 5: Master Design",
    "description": "This is an in-depth course on Design. You will learn the fundamentals and advanced topics from User 15 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course5/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 29.99,
    "level": "intermediate",
    "instructor": "user_015",
    "category": "cat_004",
    "isVerified": false,
    "verificationRejectionReason": null,
    "averageRating": 3.77,
    "totalReviews": 206,
    "totalStudentsEnrolled": 161,
    "totalDurationInMinutes": 713,
    "totalRevenueInstructor": 3892,
    "totalRevenueAdmin": 450,
    "slug": "course-title-5-master-design",
    "createdAt": "2025-09-13T15:55:42.386Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Design",
    "instructorName": "User 15 Fullname"
  },
  {
    "_id": "course_006",
    "title": "Course Title 6: Master Music",
    "description": "This is an in-depth course on Music. You will learn the fundamentals and advanced topics from User 15 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course6/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 19.99,
    "level": "advanced",
    "instructor": "user_015",
    "category": "cat_008",
    "isVerified": false,
    "verificationRejectionReason": null,
    "averageRating": 3.58,
    "totalReviews": 234,
    "totalStudentsEnrolled": 110,
    "totalDurationInMinutes": 1010,
    "totalRevenueInstructor": 77,
    "totalRevenueAdmin": 19,
    "slug": "course-title-6-master-music",
    "createdAt": "2026-05-10T04:33:13.024Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Music",
    "instructorName": "User 15 Fullname"
  },
  {
    "_id": "course_007",
    "title": "Course Title 7: Master Health & Fitness",
    "description": "This is an in-depth course on Health & Fitness. You will learn the fundamentals and advanced topics from User 8 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course7/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 29.99,
    "level": "intermediate",
    "instructor": "user_008",
    "category": "cat_009",
    "isVerified": false,
    "verificationRejectionReason": null,
    "averageRating": 3.82,
    "totalReviews": 286,
    "totalStudentsEnrolled": 875,
    "totalDurationInMinutes": 1085,
    "totalRevenueInstructor": 2348,
    "totalRevenueAdmin": 746,
    "slug": "course-title-7-master-health-&-fitness",
    "createdAt": "2025-12-05T10:23:26.153Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Health & Fitness",
    "instructorName": "User 8 Fullname"
  },
  {
    "_id": "course_008",
    "title": "Course Title 8: Master Photography",
    "description": "This is an in-depth course on Photography. You will learn the fundamentals and advanced topics from User 15 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course8/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 19.99,
    "level": "beginner",
    "instructor": "user_015",
    "category": "cat_007",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 4.71,
    "totalReviews": 96,
    "totalStudentsEnrolled": 930,
    "totalDurationInMinutes": 492,
    "totalRevenueInstructor": 2231,
    "totalRevenueAdmin": 122,
    "slug": "course-title-8-master-photography",
    "createdAt": "2025-08-23T08:18:43.472Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Photography",
    "instructorName": "User 15 Fullname"
  },
  {
    "_id": "course_009",
    "title": "Course Title 9: Master Business",
    "description": "This is an in-depth course on Business. You will learn the fundamentals and advanced topics from User 8 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course9/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 29.99,
    "level": "intermediate",
    "instructor": "user_008",
    "category": "cat_006",
    "isVerified": false,
    "verificationRejectionReason": null,
    "averageRating": 4.39,
    "totalReviews": 433,
    "totalStudentsEnrolled": 131,
    "totalDurationInMinutes": 1162,
    "totalRevenueInstructor": 2944,
    "totalRevenueAdmin": 534,
    "slug": "course-title-9-master-business",
    "createdAt": "2025-12-16T00:52:49.707Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Business",
    "instructorName": "User 8 Fullname"
  },
  {
    "_id": "course_010",
    "title": "Course Title 10: Master Business",
    "description": "This is an in-depth course on Business. You will learn the fundamentals and advanced topics from User 13 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course10/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 29.99,
    "level": "intermediate",
    "instructor": "user_013",
    "category": "cat_006",
    "isVerified": false,
    "verificationRejectionReason": null,
    "averageRating": 3.65,
    "totalReviews": 139,
    "totalStudentsEnrolled": 227,
    "totalDurationInMinutes": 308,
    "totalRevenueInstructor": 4367,
    "totalRevenueAdmin": 113,
    "slug": "course-title-10-master-business",
    "createdAt": "2025-12-16T09:33:56.663Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Business",
    "instructorName": "User 13 Fullname"
  },
  {
    "_id": "course_011",
    "title": "Course Title 11: Master Finance & Accounting",
    "description": "This is an in-depth course on Finance & Accounting. You will learn the fundamentals and advanced topics from User 8 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course11/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 29.99,
    "level": "intermediate",
    "instructor": "user_008",
    "category": "cat_012",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 3.89,
    "totalReviews": 360,
    "totalStudentsEnrolled": 230,
    "totalDurationInMinutes": 463,
    "totalRevenueInstructor": 3711,
    "totalRevenueAdmin": 697,
    "slug": "course-title-11-master-finance-&-accounting",
    "createdAt": "2025-10-14T13:21:48.003Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Finance & Accounting",
    "instructorName": "User 8 Fullname"
  },
  {
    "_id": "course_012",
    "title": "Course Title 12: Master Teaching & Academics",
    "description": "This is an in-depth course on Teaching & Academics. You will learn the fundamentals and advanced topics from User 13 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course12/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 49.99,
    "level": "advanced",
    "instructor": "user_013",
    "category": "cat_013",
    "isVerified": false,
    "verificationRejectionReason": null,
    "averageRating": 4.22,
    "totalReviews": 388,
    "totalStudentsEnrolled": 837,
    "totalDurationInMinutes": 904,
    "totalRevenueInstructor": 4084,
    "totalRevenueAdmin": 385,
    "slug": "course-title-12-master-teaching-&-academics",
    "createdAt": "2025-01-22T02:06:22.103Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Teaching & Academics",
    "instructorName": "User 13 Fullname"
  },
  {
    "_id": "course_013",
    "title": "Course Title 13: Master Personal Development",
    "description": "This is an in-depth course on Personal Development. You will learn the fundamentals and advanced topics from User 15 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course13/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 19.99,
    "level": "beginner",
    "instructor": "user_015",
    "category": "cat_010",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 4.89,
    "totalReviews": 111,
    "totalStudentsEnrolled": 7,
    "totalDurationInMinutes": 889,
    "totalRevenueInstructor": 1584,
    "totalRevenueAdmin": 52,
    "slug": "course-title-13-master-personal-development",
    "createdAt": "2026-05-18T20:47:05.754Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Personal Development",
    "instructorName": "User 15 Fullname"
  },
  {
    "_id": "course_014",
    "title": "Course Title 14: Master IT & Software",
    "description": "This is an in-depth course on IT & Software. You will learn the fundamentals and advanced topics from User 15 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course14/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 19.99,
    "level": "advanced",
    "instructor": "user_015",
    "category": "cat_011",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 3.67,
    "totalReviews": 474,
    "totalStudentsEnrolled": 343,
    "totalDurationInMinutes": 646,
    "totalRevenueInstructor": 3691,
    "totalRevenueAdmin": 104,
    "slug": "course-title-14-master-it-&-software",
    "createdAt": "2025-12-07T19:17:22.478Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "IT & Software",
    "instructorName": "User 15 Fullname"
  },
  {
    "_id": "course_015",
    "title": "Course Title 15: Master Mobile App Development",
    "description": "This is an in-depth course on Mobile App Development. You will learn the fundamentals and advanced topics from User 8 Fullname. The content is designed to take you from beginner to expert.",
    "thumbnail": "https://picsum.photos/seed/course15/800/450",
    "videoUrl": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "price": 99.99,
    "level": "intermediate",
    "instructor": "user_008",
    "category": "cat_003",
    "isVerified": true,
    "verificationRejectionReason": null,
    "averageRating": 3.64,
    "totalReviews": 292,
    "totalStudentsEnrolled": 533,
    "totalDurationInMinutes": 424,
    "totalRevenueInstructor": 4948,
    "totalRevenueAdmin": 152,
    "slug": "course-title-15-master-mobile-app-development",
    "createdAt": "2025-06-26T19:39:27.930Z",
    "updatedAt": "2026-06-06T07:55:31.030Z",
    "categoryName": "Mobile App Development",
    "instructorName": "User 8 Fullname"
  }
];
