import { type User } from "@/types/userTypes";

export const usersData: User[] = [
  {
    "_id": "user_001",
    "fullName": "User 1 Fullname",
    "email": "user1@example.com",
    "bio": "This is a bio for User 1. They are passionate about learning and teaching.",
    "highestEducation": "High School",
    "yearsOfExperience": 9,
    "avatar": "https://i.pravatar.cc/150?u=user1",
    "isVerified": false,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2026-01-05T18:51:17.021Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_002",
    "fullName": "User 2 Fullname",
    "email": "user2@example.com",
    "bio": "This is a bio for User 2. They are passionate about learning and teaching.",
    "highestEducation": "High School",
    "yearsOfExperience": 10,
    "avatar": "https://i.pravatar.cc/150?u=user2",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-07-27T12:26:43.170Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_003",
    "fullName": "User 3 Fullname",
    "email": "user3@example.com",
    "bio": "This is a bio for User 3. They are passionate about learning and teaching.",
    "highestEducation": "Bachelor's",
    "yearsOfExperience": 14,
    "avatar": "https://i.pravatar.cc/150?u=user3",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-05-04T22:07:37.652Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_004",
    "fullName": "User 4 Fullname",
    "email": "user4@example.com",
    "bio": "This is a bio for User 4. They are passionate about learning and teaching.",
    "highestEducation": "Master's",
    "yearsOfExperience": 8,
    "avatar": "https://i.pravatar.cc/150?u=user4",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-01-25T11:45:21.334Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_005",
    "fullName": "User 5 Fullname",
    "email": "user5@example.com",
    "bio": "This is a bio for User 5. They are passionate about learning and teaching.",
    "highestEducation": "Bachelor's",
    "yearsOfExperience": 0,
    "avatar": "https://i.pravatar.cc/150?u=user5",
    "isVerified": false,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-05-14T02:43:37.112Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_006",
    "fullName": "User 6 Fullname",
    "email": "user6@example.com",
    "bio": "This is a bio for User 6. They are passionate about learning and teaching.",
    "highestEducation": "High School",
    "yearsOfExperience": 0,
    "avatar": "https://i.pravatar.cc/150?u=user6",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "instructor",
    "createdAt": "2025-01-14T01:33:04.930Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_007",
    "fullName": "User 7 Fullname",
    "email": "user7@example.com",
    "bio": "This is a bio for User 7. They are passionate about learning and teaching.",
    "highestEducation": "Master's",
    "yearsOfExperience": 11,
    "avatar": "https://i.pravatar.cc/150?u=user7",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-01-13T02:13:56.021Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_008",
    "fullName": "User 8 Fullname",
    "email": "user8@example.com",
    "bio": "This is a bio for User 8. They are passionate about learning and teaching.",
    "highestEducation": "Bachelor's",
    "yearsOfExperience": 11,
    "avatar": "https://i.pravatar.cc/150?u=user8",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "instructor",
    "createdAt": "2025-07-28T08:50:51.031Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_009",
    "fullName": "User 9 Fullname",
    "email": "user9@example.com",
    "bio": "This is a bio for User 9. They are passionate about learning and teaching.",
    "highestEducation": "PhD",
    "yearsOfExperience": 15,
    "avatar": "https://i.pravatar.cc/150?u=user9",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-08-19T23:00:06.453Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_010",
    "fullName": "User 10 Fullname",
    "email": "user10@example.com",
    "bio": "This is a bio for User 10. They are passionate about learning and teaching.",
    "highestEducation": "PhD",
    "yearsOfExperience": 2,
    "avatar": "https://i.pravatar.cc/150?u=user10",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-10-08T20:04:51.581Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_011",
    "fullName": "User 11 Fullname",
    "email": "user11@example.com",
    "bio": "This is a bio for User 11. They are passionate about learning and teaching.",
    "highestEducation": "High School",
    "yearsOfExperience": 9,
    "avatar": "https://i.pravatar.cc/150?u=user11",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-11-14T00:52:16.362Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_012",
    "fullName": "User 12 Fullname",
    "email": "user12@example.com",
    "bio": "This is a bio for User 12. They are passionate about learning and teaching.",
    "highestEducation": "Master's",
    "yearsOfExperience": 12,
    "avatar": "https://i.pravatar.cc/150?u=user12",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2026-02-02T04:06:58.963Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_013",
    "fullName": "User 13 Fullname",
    "email": "user13@example.com",
    "bio": "This is a bio for User 13. They are passionate about learning and teaching.",
    "highestEducation": "Bachelor's",
    "yearsOfExperience": 11,
    "avatar": "https://i.pravatar.cc/150?u=user13",
    "isVerified": false,
    "verificationRejectionReason": null,
    "role": "instructor",
    "createdAt": "2025-05-23T04:26:59.901Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_014",
    "fullName": "User 14 Fullname",
    "email": "user14@example.com",
    "bio": "This is a bio for User 14. They are passionate about learning and teaching.",
    "highestEducation": "Master's",
    "yearsOfExperience": 4,
    "avatar": "https://i.pravatar.cc/150?u=user14",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "student",
    "createdAt": "2025-06-16T14:24:57.550Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  },
  {
    "_id": "user_015",
    "fullName": "User 15 Fullname",
    "email": "user15@example.com",
    "bio": "This is a bio for User 15. They are passionate about learning and teaching.",
    "highestEducation": "PhD",
    "yearsOfExperience": 4,
    "avatar": "https://i.pravatar.cc/150?u=user15",
    "isVerified": true,
    "verificationRejectionReason": null,
    "role": "instructor",
    "createdAt": "2026-05-14T17:27:38.734Z",
    "updatedAt": "2026-06-06T07:55:31.030Z"
  }
];
